"""Natural-language query layer for the car-sales dashboard.

Architecture
------------
The user asks a question in plain English or Chinese.
Claude receives a compact data summary (date range, countries, total rows) as
context, then decides which tools to call to answer the question.
Each tool wraps existing analyzer.py functions — no raw SQL is ever passed to
or generated by the LLM.

Claude Sonnet 4.6 is used by default; override with CHAT_MODEL env var.
Requires ANTHROPIC_API_KEY in the environment (or .env file).

Public API
----------
    answer(question: str, session: Session) -> str
"""

from __future__ import annotations

import json
import os
from typing import Any

import pandas as pd

from .analyzer import summarize_all, summarize_country, country_slug
from .db import load_sales_df

# ── 默认模型，可用环境变量覆盖 ───────────────────────────────────────────────
_DEFAULT_MODEL = "claude-sonnet-4-6"

# ── 工具定义（传给 Claude API 的 JSON Schema）──────────────────────────────

_TOOLS: list[dict] = [
    {
        "name": "get_global_summary",
        "description": (
            "Return global KPIs across all countries: total sales, total quantity, "
            "order count, country count, date range, and a ranked table of sales by country. "
            "Optionally filter by date range."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "start_date": {
                    "type": "string",
                    "description": "ISO date string YYYY-MM-DD (inclusive). Omit for no lower bound.",
                },
                "end_date": {
                    "type": "string",
                    "description": "ISO date string YYYY-MM-DD (inclusive). Omit for no upper bound.",
                },
            },
            "required": [],
        },
    },
    {
        "name": "get_country_detail",
        "description": (
            "Return detailed KPIs for a single country: total sales & quantity, "
            "monthly/quarterly trend with period-over-period and year-over-year deltas, "
            "and a ranked list of top car models by sales."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "country": {
                    "type": "string",
                    "description": "Exact country name as it appears in the data (e.g. 'China', 'Germany').",
                },
                "granularity": {
                    "type": "string",
                    "enum": ["M", "Q", "Y"],
                    "description": "Time-series grain: M=monthly, Q=quarterly, Y=yearly. Default M.",
                },
            },
            "required": ["country"],
        },
    },
    {
        "name": "compare_countries",
        "description": (
            "Compare two or more countries side by side: total sales, quantity, "
            "and share of overall sales for each."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "countries": {
                    "type": "array",
                    "items": {"type": "string"},
                    "description": "List of country names to compare.",
                },
                "start_date": {"type": "string", "description": "ISO date YYYY-MM-DD."},
                "end_date": {"type": "string", "description": "ISO date YYYY-MM-DD."},
            },
            "required": ["countries"],
        },
    },
    {
        "name": "get_top_models",
        "description": (
            "Return the top N car models ranked by total sales, optionally filtered "
            "to a specific country."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "top_n": {
                    "type": "integer",
                    "description": "How many top models to return. Default 10.",
                },
                "country": {
                    "type": "string",
                    "description": "Restrict to this country. Omit for all countries.",
                },
            },
            "required": [],
        },
    },
    {
        "name": "get_trend",
        "description": (
            "Return the sales trend over time for a given granularity, optionally "
            "filtered to one country. Useful for 'is sales growing?', 'when was the peak?', etc."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "granularity": {
                    "type": "string",
                    "enum": ["M", "Q", "Y"],
                    "description": "Time grain: M=monthly, Q=quarterly, Y=yearly.",
                },
                "country": {
                    "type": "string",
                    "description": "Restrict to this country. Omit for global trend.",
                },
            },
            "required": ["granularity"],
        },
    },
]

# ── 工具执行层（真实 Python 计算，绝不向 LLM 暴露原始 SQL）──────────────

def _run_tool(name: str, inputs: dict, df: pd.DataFrame) -> Any:
    """把 LLM 的工具调用路由到 analyzer 函数，返回可序列化的 dict/list。"""

    def _ts(s: str | None) -> pd.Timestamp | None:
        return pd.Timestamp(s) if s else None

    if name == "get_global_summary":
        g = summarize_all(
            df,
            start=_ts(inputs.get("start_date")),
            end=_ts(inputs.get("end_date")),
        )
        rows = g.by_country[["country", "display_name", "sales", "quantity", "orders"]].copy()
        rows["sales"] = rows["sales"].round(0).astype(int)
        return {
            "total_sales": round(g.total_sales, 0),
            "total_quantity": g.total_quantity,
            "order_count": g.order_count,
            "country_count": g.country_count,
            "date_range": [str(g.date_range[0])[:10], str(g.date_range[1])[:10]],
            "by_country": rows.to_dict(orient="records"),
        }

    if name == "get_country_detail":
        country = inputs["country"]
        gran = inputs.get("granularity", "M")
        # 允许大小写不敏感匹配
        country_map = {c.lower(): c for c in df["country"].unique()}
        country = country_map.get(country.lower(), country)
        s = summarize_country(df, country, granularity=gran)
        trend = s.trend[["period_label", "sales", "quantity", "pop_pct", "yoy_pct"]].copy()
        trend["sales"] = trend["sales"].round(0).astype(int)
        trend["pop_pct"] = trend["pop_pct"].round(1)
        trend["yoy_pct"] = trend["yoy_pct"].round(1)
        return {
            "country": s.country,
            "total_sales": round(s.total_sales, 0),
            "total_quantity": s.total_quantity,
            "date_range": [str(s.date_range[0])[:10] if s.date_range[0] else None,
                           str(s.date_range[1])[:10] if s.date_range[1] else None],
            "top_models": s.top_models.to_dict(orient="records"),
            "trend": trend.to_dict(orient="records"),
        }

    if name == "compare_countries":
        countries = inputs["countries"]
        g = summarize_all(
            df,
            start=_ts(inputs.get("start_date")),
            end=_ts(inputs.get("end_date")),
            countries=countries,
        )
        total = g.total_sales or 1
        rows = g.by_country[["country", "display_name", "sales", "quantity"]].copy()
        rows["share_pct"] = (rows["sales"] / total * 100).round(1)
        rows["sales"] = rows["sales"].round(0).astype(int)
        return rows.to_dict(orient="records")

    if name == "get_top_models":
        top_n = int(inputs.get("top_n", 10))
        country = inputs.get("country")
        sub = df
        if country:
            country_map = {c.lower(): c for c in df["country"].unique()}
            country = country_map.get(country.lower(), country)
            sub = df[df["country"] == country]
        models = (
            sub.groupby("model", as_index=False)
            .agg(sales=("sales", "sum"), quantity=("quantity", "sum"))
            .sort_values("sales", ascending=False)
            .head(top_n)
            .reset_index(drop=True)
        )
        models["sales"] = models["sales"].round(0).astype(int)
        return models.to_dict(orient="records")

    if name == "get_trend":
        gran = inputs["granularity"]
        country = inputs.get("country")
        if country:
            country_map = {c.lower(): c for c in df["country"].unique()}
            country = country_map.get(country.lower(), country)
            s = summarize_country(df, country, granularity=gran)
            trend = s.trend
        else:
            g = summarize_all(df, granularity=gran)
            trend = g.trend
        out = trend[["period_label", "sales", "quantity", "pop_pct", "yoy_pct"]].copy()
        out["sales"] = out["sales"].round(0).astype(int)
        out["pop_pct"] = out["pop_pct"].round(1)
        out["yoy_pct"] = out["yoy_pct"].round(1)
        return out.to_dict(orient="records")

    return {"error": f"Unknown tool: {name}"}


# ── 主入口 ─────────────────────────────────────────────────────────────────

def answer(question: str, session) -> str:
    """Run the tool-use loop and return a plain-text answer.

    Args:
        question: User's natural-language question (English or Chinese).
        session: SQLAlchemy Session — used to load the data once.

    Returns:
        A plain-text / markdown answer string.

    Raises:
        RuntimeError: If ANTHROPIC_API_KEY is not set.
        ImportError: If the anthropic package is not installed.
    """
    import anthropic  # 延迟导入，仅在实际调用时强依赖

    api_key = os.getenv("ANTHROPIC_API_KEY")
    if not api_key:
        raise RuntimeError(
            "ANTHROPIC_API_KEY is not set. Add it to your .env file."
        )

    df = load_sales_df(session)

    # 给模型一份轻量的数据概览，帮助它理解数据集边界（避免幻觉）
    countries_list = sorted(df["country"].unique().tolist()) if not df.empty else []
    context = (
        f"You are a data analyst assistant for a car-sales dashboard. "
        f"The dataset covers {len(df):,} sales records across "
        f"{df['country'].nunique() if not df.empty else 0} countries "
        f"from {str(df['date'].min())[:10] if not df.empty else 'N/A'} "
        f"to {str(df['date'].max())[:10] if not df.empty else 'N/A'}. "
        f"Available countries: {', '.join(countries_list)}. "
        "Use the provided tools to retrieve data before answering. "
        "Keep answers concise and data-driven."
    )

    client = anthropic.Anthropic(api_key=api_key)
    model = os.getenv("CHAT_MODEL", _DEFAULT_MODEL)
    messages = [{"role": "user", "content": question}]

    # 最多 5 轮工具调用（防止意外死循环）
    for _ in range(5):
        response = client.messages.create(
            model=model,
            max_tokens=1024,
            system=context,
            tools=_TOOLS,
            messages=messages,
        )

        # 没有工具调用 → 直接取文本返回
        if response.stop_reason == "end_turn":
            return _extract_text(response)

        # 有工具调用 → 执行并回传结果
        if response.stop_reason == "tool_use":
            # 把模型回复（含工具调用块）追加到消息链
            messages.append({"role": "assistant", "content": response.content})

            # 执行每个工具调用并收集结果
            tool_results = []
            for block in response.content:
                if block.type == "tool_use":
                    result = _run_tool(block.name, block.input, df)
                    tool_results.append({
                        "type": "tool_result",
                        "tool_use_id": block.id,
                        "content": json.dumps(result, ensure_ascii=False, default=str),
                    })

            messages.append({"role": "user", "content": tool_results})
            continue

        # 其他 stop_reason（max_tokens 等）
        break

    return _extract_text(response)


def _extract_text(response) -> str:
    """从 Anthropic response 提取纯文本内容。"""
    parts = [b.text for b in response.content if hasattr(b, "text")]
    return "\n".join(parts).strip() or "(no response)"
